Project2/force-app/main/default/objects/Product2/fields/inStockQuantity__c.field-meta.xml
<CustomField>
    <fullName>inStockQuantity__c</fullName>
    <description>Quantity of Units in Stock</description>
    <label>in Stock Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>These are the units in the warehouse</description>
    <label>Units</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lux Black</fullName>
            </value>
            <value>
                <fullName>Lux White</fullName>
            </value>
            <value>
                <fullName>Bold White</fullName>
            </value>
            <value>
                <fullName>Bold Black</fullName>
            </value>
            <value>
                <fullName>Bold White Chrome</fullName>
            </value>
            <value>
                <fullName>Bold Black Chrome</fullName>
            </value>
            <value>
                <fullName>Bidet Mini</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductsController.cls
public with sharing class ProductsController {
    @AuraEnabled
    public static List <Product2> readProducts() {
        //Query products
       List<Product2> prdList = [SELECT Id, Name, Description, ProductCode, Units__c, inStockQuantity__c 
                                    FROM Product2 
                                    WHERE IsActive = True];
        //return list of accounts
        return prdList;     
    }
}