Project2/force-app/main/default/objects/Order/fields/LastLocation__c.field-meta.xml
<CustomField>
    <fullName>LastLocation__c</fullName>
    <label>LastLocation</label>
    <type>TextArea</type>
</CustomField>

Project2/force-app/main/default/objects/Order/fields/Lat__c.field-meta.xml
<CustomField>
    <fullName>Lat__c</fullName>
    <label>Lat__c</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Order/fields/Lon__c.field-meta.xml
<CustomField>
    <fullName>Lon__c</fullName>
    <label>Lon__c</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TrackingNumber__c.field-meta.xml
<CustomField>
    <fullName>TrackingNumber__c</fullName>
    <displayFormat>{YYYY}{MM}{DD}{0}</displayFormat>
    <label>TrackingNumber</label>
    <type>AutoNumber</type>
</CustomField>

Project2/force-app/main/default/classes/OrderSearchCon.cls
public with sharing class OrderSearchCon {
    
    @AuraEnabled
    public static Order GetOrder(string orderTN) {
        System.debug(orderTN);
        orderTN = orderTN + '%';
        order ret;

        ret = [SELECT Id, TrackingNumber__c, OrderNumber, TotalAmount, Status, LastLocation__c, Lat__c, Lon__c, AccountId FROM Order WHERE TrackingNumber__c LIKE :orderTN LIMIT 1];
        
        return ret;
    }
}