Project2/force-app/main/default/objects/Order/fields/Lat__c.field-meta.xml
<CustomField>
    <fullName>Lat__c</fullName>
    <label>Lat__c</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Order/fields/Lon__c.field-meta.xml
<CustomField>
    <fullName>Lon__c</fullName>
    <label>Lon__c</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TrackingNumber__c.field-meta.xml
<CustomField>
    <fullName>TrackingNumber__c</fullName>
    <displayFormat>{YYYY}{MM}{DD}{0}</displayFormat>
    <label>TrackingNumber</label>
    <type>AutoNumber</type>
</CustomField>

Project2/force-app/main/default/classes/OrderMapController.cls
public with sharing class OrderMapController {
    
    @AuraEnabled
    public static Order getOrderLocation(string orderTN) {
        System.debug(orderTN);
        orderTN = orderTN + '%';
        order ret;

        ret = [SELECT TrackingNumber__c, Lat__c, Lon__c FROM Order WHERE TrackingNumber__c LIKE :orderTN LIMIT 1];
        
        return ret;
    }
    // currently the lightning map works on order IDs, need to find away to do the same with order number
}